# Generated by Django 4.2.11 on 2024-03-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_domicilio_persona_domocilio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='domocilio',
            new_name='domicilio',
        ),
    ]
